In [1]:
import os
import topogenesis as tg
import pyvista as pv
import trimesh as tm
import numpy as np
import pickle
import csv

In [32]:
#This script scales the data found in the sound.gh file to useable data between 0.0 - 1.0
########################################################################################
#Loading the complete lattice for reference and shape
lattice_path = os.path.relpath("data\lattice_complete_3_6.csv")
envelope_lattice = tg.lattice_from_csv(lattice_path)
shape = envelope_lattice.shape
base_list = np.zeros(shape)
########################################################################################


########################################################################################
#Load the pickled database from sound.gh
full_list = []
for i in range(0,12):
    file_path = "data\sound\sound_z_"+str(i)+".txt"
    with open(file_path, "rb") as fp:   # Unpickling
        current_list = pickle.load(fp)
        print(current_list)
    for j in range(len(current_list)):
        full_list.append(current_list[j])

#Translate [x,y,z,val] to latttice with only val
val_list = []
for i in range(len(full_list)):
    x = full_list[i][0]
    y = full_list[i][1]
    z = full_list[i][2]
    val = full_list[i][3]
    base_list[x][y][z] = val
    val_list.append(val)

#Creating a scalar in which min = 0.0 and max = 1.0
max_val = max(val_list)
min_val = min(val_list)
scalar = max_val - min_val

#Scaling the values with the found scalar
for i in range(len(base_list)):
    for j in range(len(base_list[0])):
        for k in range(len(base_list[0][0])):
            if base_list[i][j][k] != 0:
                base_list[i][j][k] -= min_val
                base_list[i][j][k] /= scalar
                temp_val = base_list[i][j][k]-0.5
                base_list[i][j][k] = 0.5 - temp_val

#Export the sound lattice               
sound_lattice = tg.to_lattice(base_list, envelope_lattice)
csv_path_lattice = os.path.relpath("data\sound_3_6.csv")
sound_lattice.to_csv(csv_path_lattice)
########################################################################################
print("done")



[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
[[0, 0, 0,